/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diagrameditor;

import core.webmet.EJBWebServicev20;
import core.webmet.GenerateUrlIndata;
import core.webmet.GenerateUrlResponse;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.Document;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author MPA
 */
public class CuestionarioPanel extends EditorPanel {

    /**
     * Creates new form CuestionarioPanel
     */
    public CuestionarioPanel() {
        initComponents();
        miInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanel = new javax.swing.JTabbedPane();
        tabEncabezado = new javax.swing.JPanel();
        tabPrecondiciones = new javax.swing.JPanel();
        tabReporte = new javax.swing.JPanel();
        cardPanel = new javax.swing.JPanel();
        encabezadoCard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        precondicionesCard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        reporteCard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        tabbedPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPanelStateChanged(evt);
            }
        });

        javax.swing.GroupLayout tabEncabezadoLayout = new javax.swing.GroupLayout(tabEncabezado);
        tabEncabezado.setLayout(tabEncabezadoLayout);
        tabEncabezadoLayout.setHorizontalGroup(
            tabEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        tabEncabezadoLayout.setVerticalGroup(
            tabEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Encabezado", tabEncabezado);

        javax.swing.GroupLayout tabPrecondicionesLayout = new javax.swing.GroupLayout(tabPrecondiciones);
        tabPrecondiciones.setLayout(tabPrecondicionesLayout);
        tabPrecondicionesLayout.setHorizontalGroup(
            tabPrecondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        tabPrecondicionesLayout.setVerticalGroup(
            tabPrecondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Precondiciones", tabPrecondiciones);

        javax.swing.GroupLayout tabReporteLayout = new javax.swing.GroupLayout(tabReporte);
        tabReporte.setLayout(tabReporteLayout);
        tabReporteLayout.setHorizontalGroup(
            tabReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        tabReporteLayout.setVerticalGroup(
            tabReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Reporte", tabReporte);

        cardPanel.setLayout(new java.awt.CardLayout());

        jLabel4.setText("Nombre propietario");

        jLabel5.setText("Nombre reporte");

        jLabel6.setText("Lugar");

        jLabel7.setText("Prefix");

        javax.swing.GroupLayout encabezadoCardLayout = new javax.swing.GroupLayout(encabezadoCard);
        encabezadoCard.setLayout(encabezadoCardLayout);
        encabezadoCardLayout.setHorizontalGroup(
            encabezadoCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encabezadoCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(encabezadoCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        encabezadoCardLayout.setVerticalGroup(
            encabezadoCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encabezadoCardLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        cardPanel.add(encabezadoCard, "encabezadoCard");

        jLabel2.setText("Precondiciones");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout precondicionesCardLayout = new javax.swing.GroupLayout(precondicionesCard);
        precondicionesCard.setLayout(precondicionesCardLayout);
        precondicionesCardLayout.setHorizontalGroup(
            precondicionesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(precondicionesCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(precondicionesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addGroup(precondicionesCardLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        precondicionesCardLayout.setVerticalGroup(
            precondicionesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(precondicionesCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardPanel.add(precondicionesCard, "precondicionesCard");

        jLabel3.setText("Reporte");

        javax.swing.GroupLayout reporteCardLayout = new javax.swing.GroupLayout(reporteCard);
        reporteCard.setLayout(reporteCardLayout);
        reporteCardLayout.setHorizontalGroup(
            reporteCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reporteCardLayout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(150, 150, 150))
        );
        reporteCardLayout.setVerticalGroup(
            reporteCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteCardLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel3)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        cardPanel.add(reporteCard, "reporteCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel)
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabbedPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPanelStateChanged
        try {
            CardLayout card = (CardLayout) cardPanel.getLayout();
            String tab = tabbedPanel.getTitleAt(tabbedPanel.getSelectedIndex());
            switch (tab) {
                case "Encabezado":
                    card.show(cardPanel, "encabezadoCard");
                    break;
                case "Precondiciones":
                    card.show(cardPanel, "precondicionesCard");
                    break;
                case "Reporte":
                    card.show(cardPanel, "reporteCard");
                    break;
            }
        } catch (Exception e) {
            System.out.println("Exception: " + e);
        }
    }//GEN-LAST:event_tabbedPanelStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel encabezadoCard;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel precondicionesCard;
    private javax.swing.JPanel reporteCard;
    private javax.swing.JPanel tabEncabezado;
    private javax.swing.JPanel tabPrecondiciones;
    private javax.swing.JPanel tabReporte;
    private javax.swing.JTabbedPane tabbedPanel;
    // End of variables declaration//GEN-END:variables

    private void miInit() {
        //List diccionario = new ArrayList();
        //diccionario.add("Hola");
        //diccionario.add("Hoaodlao");
        //new AutoCompletar(jTextArea1, diccionario).init();
        Precondiciones precond = new Precondiciones();
        new AutoCompletar(jTextArea1, precond.getFunciones()).init();
        
    }
}
